apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: ingress
  labels:
    purpose: demonstrate-command
spec:
  selector:
    matchLabels:
      purpose: demonstrate-command
  template:
    metadata:
      labels:
        purpose: demonstrate-command
    spec:
      containers:
      - name: nginx
        image: nginx-controller:v0.49