name: Coverage-Check

on:
  workflow_call:
    inputs:
      COVERAGELIMIT: 
        required: true
        type: string
      SHA: 
        required: true
        type: string
jobs: 
  test-coverage:
    name: Check coverage
    runs-on: ubuntu-latest
    steps:
      - name: print-sha
        run: |
          echo "${{ inputs.SHA }} , ${{ github.sha }}, ${{ secrets.COVERALLS_TOKEN }}"

      - name: Get Coverage Data from Coveralls by commit SHA
        id: coveralls
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.COVERALLS_TOKEN }}" \
                          "https://coveralls.io/builds/${{ inputs.SHA }}.json")
          coverage=$(echo $response | jq '.covered_percent')
          echo "COVERAGE=$coverage" >> $GITHUB_ENV
      
      - name: Use Coverage Data
        run: |  
          echo "Current Coverage is: $COVERAGE"

      - name: test coverage
        run: |    
          if (( $(echo "$COVERAGE < ${{ inputs.COVERAGELIMIT }}" |bc -l) )); then
            echo "Code coverage is less than ${{ inputs.COVERAGELIMIT }}%, blocking the PR"
            exit 1
          fi          