name: Push to Armosec Repo

on:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      PRIVATE_REPO_URL: <private-repo-url>
      PRIVATE_REPO_USERNAME: ${{ secrets.PRIVATE_REPO_USERNAME }}
      PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git Credentials
        run: |
          git config --global user.name "${PRIVATE_REPO_USERNAME}"
          git config --global user.email "${PRIVATE_REPO_EMAIL}"

      - name: Push Changes
        run: |
          git remote add private-repo "${PRIVATE_ARMOSEC_URL}"
          git checkout -b temp-branch
          git add .
          git commit -m "Pushing changes from source repo"
          git push private-repo temp-branch:main