name: Push to regolibrary-dev

on:
  push:
    branches: [master]

env:
  GH_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ env.GH_ACCESS_TOKEN }}

    - run: git config --global url.https://${{ env.GH_ACCESS_TOKEN }}@github.com/armosec/.insteadOf https://github.com/armosec/
    - run: git config --global url.https://${{ env.GH_ACCESS_TOKEN }}@github.com/kubescape/.insteadOf https://github.com/kubescape/
  
    - name: Run export script
      run: |
        OUTPUT=pre-release python ./scripts/export.py
        rm -r -f releaseDev
        cp -R pre-release releaseDev

    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -a -m "Updating releaseDev files $(date)"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ env.GH_ACCESS_TOKEN }}
        repository: kubescape/regolibrary-dev
        force: true
